### ISSUE TITLE
Needs code

### ISSUE THREAD

**Issue by zxqx** [acdibble/rasp-pi-speed-bot#1]
Tried to pull the project and there's nothing there.

**Comment by jpangelle** [comment]
try using `npm do-project`

**Comment by acdibble** [comment]
Still working out naming conventions. The committee is deadlocked on reverse camel case or all caps skewer case for constants.

**Comment by zxqx** [comment]
Real Gs know that running `npm do-project` directly is archaic. You need to set up a serverless cloud function so you can scale your project generation horizontally and infinitely.
